server:
  port: 8082
  connection:
  - timeout: 4000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/marketplace?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
  flyway:
    clean-disabled: false
    clean-on-validation-error: false
    locations: classpath:db/migration
    table: schema_history
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default-schema: usuario
    show-sql: true
  thymeleaf:
    cache: false
